name: OreoEssentials
version: "1.0-SNAPSHOT"
main: fr.elias.oreoEssentials.OreoEssentials
api-version: "1.21"

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  spawn:
    description: Teleport to spawn
    permission: oreo.spawn

  setspawn:
    description: Set the server spawn
    permission: oreo.setspawn

  back:
    description: Return to your last location
    permission: oreo.back

  warp:
    description: Teleport to a warp
    permission: oreo.warp
    usage: "/warp <name>"

  setwarp:
    description: Create or overwrite a warp
    permission: oreo.setwarp
    usage: "/setwarp <name>"

  delwarp:
    description: Delete a warp
    permission: oreo.delwarp
    usage: "/delwarp <name>"

  home:
    description: Teleport to a home
    permission: oreo.home
    usage: "/home <name>"

  sethome:
    description: Set a home
    permission: oreo.sethome
    usage: "/sethome <name>"

  delhome:
    description: Delete a home
    permission: oreo.delhome
    usage: "/delhome <name>"

  homes:
    description: List your homes or teleport to one
    aliases: [listhomes]
    permission: oreo.homes
    usage: "/homes [name]"

  tpa:
    description: Request to teleport to a player
    permission: oreo.tpa
    usage: "/tpa <player>"

  tpaccept:
    description: Accept a teleport request
    permission: oreo.tpa

  tpdeny:
    description: Deny a teleport request
    permission: oreo.tpa

  fly:
    description: Toggle flight
    permission: oreo.fly

  heal:
    description: Heal yourself or others
    permission: oreo.heal
    usage: "/heal [player]"

  feed:
    description: Feed yourself or others
    permission: oreo.feed
    usage: "/feed [player]"

  msg:
    description: Private message a player
    permission: oreo.msg
    usage: "/msg <player> <message>"

  reply:
    description: Reply to the last private message
    aliases: [r]
    permission: oreo.msg

  broadcast:
    description: Broadcast a message
    permission: oreo.broadcast
    usage: "/broadcast <message>"

  # Economy commands
  money:
    description: View/give/take/set player balances
    permission: oreo.money
    usage: "/money [player] | /money <give|take|set> <player> <amount>"

  pay:
    description: Pay a player money
    permission: oreo.pay
    usage: "/pay <player> <amount>"

  cheque:
    description: Create/redeem money cheques
    permission: rabbiteconomy.cheque.create
    usage: "/cheque <create|redeem> ..."

  # Utilities
  deathback:
    description: Teleport to your last death location
    permission: oreo.deathback
    usage: "/deathback"

  # God mode
  god:
    description: Toggle invulnerability (god mode)
    permission: oreo.god
    usage: "/god [player]"

  # Portals / JumpPads
  portal:
    description: Manage cuboid portals
    permission: oreo.portal
    usage: "/portal <pos1|pos2|create|remove|list|info>"

  jumpad:
    description: Manage jump pads
    permission: oreo.jumpad
    usage: "/jumpad <create|remove|list|info>"

  tp:
    description: Teleport to a player, or teleport a player to another
    permission: oreo.tp
    usage: "/tp <player> [target]"

  vanish:
    description: Toggle vanish (hide from players and mobs)
    aliases: [v]
    permission: oreo.vanish
    usage: "/vanish [on|off]"

  ban:
    description: Ban a player (optionally temporary)
    permission: oreo.ban
    usage: "/ban <player> [duration] [reason...]"

  unban:
    description: Unban a player
    permission: oreo.unban
    usage: "/unban <player>"

  kick:
    description: Kick a player
    permission: oreo.kick
    usage: "/kick <player> [reason...]"

  freeze:
    description: Freeze/unfreeze a player
    permission: oreo.freeze
    usage: "/freeze <player> [on|off]"

  enchant:
    description: Enchant the item in your hand
    permission: oreo.enchant
    usage: "/enchant <enchantment> [level] [unsafe] [ignoreConflicts]"

  afelius:
    description: Reload Afelius chat configs
    aliases: [af]
    permission: oreo.afelius.reload
    usage: "/afelius reload <all|config|chat-format>"

  mute:
    description: Mute a player for a duration (e.g., 10m) with optional reason
    permission: oreo.mute
    usage: "/mute <player> <duration> [reason]"

  unmute:
    description: Unmute a player
    permission: oreo.unmute
    usage: "/unmute <player>"

  # Proxy commands
  oe:
    description: OreoEssentials utility root command
    permission: oreo.oe
    usage: "/oe server <servername>"

  oeserver:
    description: Switch to another server on the proxy
    aliases: [server]
    permission: oreo.server
    usage: "/oeserver <server>"

  # NEW: skin/clone/head
  skin:
    description: Apply another player's skin to yourself (supports offline names)
    permission: oreo.skin
    usage: "/skin <player>"

  clone:
    description: Clone another player's identity (skin + display name if supported)
    permission: oreo.clone
    usage: "/clone <player>"

  head:
    description: Give yourself a player head of the specified player
    permission: oreo.head
    usage: "/head <player>"

  # NEW: nick
  nick:
    description: Change your displayed name (chat + tab) or reset it
    permission: oreo.nick
    usage: "/nick <newName> | /nick unnick"

permissions:
  oreo.*:
    description: All OreoEssentials features
    default: op
    children:
      oreo.spawn: true
      oreo.setspawn: true
      oreo.back: true
      oreo.warp: true
      oreo.setwarp: true
      oreo.delwarp: true
      oreo.home: true
      oreo.sethome: true
      oreo.delhome: true
      oreo.homes: true
      oreo.tpa: true
      oreo.fly: true
      oreo.heal: true
      oreo.feed: true
      oreo.msg: true
      oreo.broadcast: true
      oreo.money: true
      oreo.money.give: true
      oreo.money.take: true
      oreo.money.set: true
      oreo.pay: true
      oreo.cheque.create: true
      oreo.cheque.redeem: true
      oreo.deathback: true
      oreo.god: true
      oreo.portal: true
      oreo.jumpad: true
      oreo.tp: true
      oreo.vanish: true
      oreo.ban: true
      oreo.unban: true
      oreo.kick: true
      oreo.freeze: true
      oreo.enchant: true
      oreo.enchant.unsafe: true
      oreo.enchant.ignoreconflicts: true
      oreo.afelius.reload: true
      oreo.mute: true
      oreo.unmute: true
      oreo.oe: true
      oreo.server: true
      oreo.skin: true
      oreo.clone: true
      oreo.head: true
      oreo.nick: true
      # legacy nodes used in your economy handlers
      rabbiteconomy.money.give: true
      rabbiteconomy.money.take: true
      rabbiteconomy.money.set: true
      rabbiteconomy.cheque.create: true
      rabbiteconomy.cheque.redeem: true

  # Essentials basics
  oreo.spawn: { default: true }
  oreo.setspawn: { default: op }
  oreo.back: { default: true }
  oreo.warp: { default: true }
  oreo.setwarp: { default: op }
  oreo.delwarp: { default: op }
  oreo.home: { default: true }
  oreo.sethome: { default: true }
  oreo.delhome: { default: true }
  oreo.homes: { default: true }
  oreo.tpa: { default: true }
  oreo.fly: { default: op }
  oreo.heal: { default: op }
  oreo.feed: { default: op }
  oreo.msg: { default: true }
  oreo.broadcast: { default: op }
  oreo.tp: { default: op }
  oreo.vanish: { default: op }

  # Economy base + sub-perms
  oreo.money: { default: op }
  oreo.money.give: { default: op }
  oreo.money.take: { default: op }
  oreo.money.set: { default: op }
  oreo.pay: { default: true }
  oreo.cheque.create: { default: op }
  oreo.cheque.redeem: { default: true }

  # Moderation
  oreo.ban: { default: op }
  oreo.unban: { default: op }
  oreo.kick: { default: op }
  oreo.freeze: { default: op }
  oreo.mute: { default: op }
  oreo.unmute: { default: op }

  # Proxy/root
  oreo.oe: { default: true }
  oreo.server: { default: true }

  # Enchant
  oreo.enchant: { default: op }
  oreo.enchant.unsafe: { default: op }
  oreo.enchant.ignoreconflicts: { default: op }

  # Utilities
  oreo.deathback: { default: true }
  oreo.god: { default: op }
  oreo.afelius.reload: { default: op }

  # New cosmetic commands
  oreo.skin: { default: op }
  oreo.clone: { default: op }
  oreo.head: { default: op }
  oreo.nick: { default: op }

  # Portals / JumpPads
  oreo.portal: { default: op }
  oreo.jumpad: { default: op }

  # Legacy RabbitEconomy nodes (compat)
  rabbiteconomy.money.give: { default: op }
  rabbiteconomy.money.take: { default: op }
  rabbiteconomy.money.set: { default: op }
  rabbiteconomy.cheque.create: { default: op }
  rabbiteconomy.cheque.redeem: { default: true }
